export const ERROR_DOWNLOAD_FROM_OPEN_WEATHER_MAP =
  "Failed to load resource: the server responded with a status of 404 (Not Found)";
export const ERROR_DOWNLOAD_FROM_WEATHERSTACK =
  "Your API request failed. Please try again or contact support.";
export const SEARCH_CITY = "SEARCH_CITY";
export const DISPLAY_TEMPERATURE = "DISPLAY_TEMPERATURE";
export const CHANGE_INPUT_SEARCH = "CHANGE_INPUT_SEARCH";
export const SELECT_ON_CHANGE = "SELECT_ON_CHANGE";
export const SET_DATA_FROM_OPEN_WEATHER_MAP_SUCCESS =
  "SET_DATA_FROM_OPEN_WEATHER_MAP_SUCCESS";
export const SET_DATA_FROM_WEATHER_STACK_SUCCESS =
  "SET_DATA_FROM_WEATHER_STACK_SUCCESS";
export const LOAD_DATA_FROM_OPENWEATHERMAP = "LOAD_DATA_FROM_OPENWEATHERMAP";
export const LOAD_DATA_FROM_WEATHERSTACK = "LOAD_DATA_FROM_WEATHERSTACK";
export const LOAD_GEOLOCATION_FROM_OPENWEATHERMAP =
  "LOAD_GEOLOCATION_FROM_OPENWEATHERMAP";
export const START_DOWNLOAD = "START_DOWNLOAD";
export const ERROR_DOWNLOAD = "ERROR_DOWNLOAD";
export const END_DOWNLOAD = "END_DOWNLOAD";
export const SELECT_API = "SELECT_API";
