export const ERROR_DOWNLOAD_FROM_OPEN_WEATHER_MAP =
  "Failed to load resource: the server responded with a status of 404 (Not Found)";
export const ERROR_DOWNLOAD_FROM_WEATHERSTACK =
  "Your API request failed. Please try again or contact support.";
export const SEARCH_CITY = "SEARCH_CITY";
export const DISPLAY_TEMPERATURE = "DISPLAY_TEMPERATURE";
export const CHANGE_INPUT_SEARCH = "CHANGE_INPUT_SEARCH";
export const SELECT_ON_CHANGE = "SELECT_ON_CHANGE";
export const SET_DATA_FROM_OPEN_WEATHER_MAP_SUCCESS =
  "SET_DATA_FROM_OPEN_WEATHER_MAP_SUCCESS";
export const SET_DATA_FROM_WEATHER_STACK_SUCCESS =
  "SET_DATA_FROM_WEATHER_STACK_SUCCESS";
export const LOAD_DATA_FROM_APIS = "LOAD_DATA_FROM_APIS";
export const LOAD_DATA_FROM_WEATHERSTACK = "LOAD_DATA_FROM_WEATHERSTACK";
export const LOAD_GEOLOCATION_FROM_OPENWEATHERMAP =
  "LOAD_GEOLOCATION_FROM_OPENWEATHERMAP";
export const START_DOWNLOAD = "START_DOWNLOAD";
export const ERROR_DOWNLOAD = "ERROR_DOWNLOAD";
export const END_DOWNLOAD = "END_DOWNLOAD";
export const SELECT_API = "SELECT_API";
export const NEW_USER_REGISTRATION = "NEW_USER_REGISTRATION";
export const NEW_USER_REGISTRATION_FAILED = "NEW_USER_REGISTRATION_FAILED";
export const NEW_USER_REGISTRATION_SUCCESS = "NEW_USER_REGISTRATION_SUCCESS";
export const NEW_USER_REGISTRATION_STATUS = "New user registration success";
export const USER_LOGIN = "USER_LOGIN";
export const LOGIN_WITH_EMAIL_FAILED = "LOGIN_WITH_EMAIL_FAILED";
export const USER_LOGIN_FAILED = "USER_LOGIN_FAILED";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const LOGOUT_USER = "LOGOUT_USER";
export const SET_USER_EMAIL = "SET_USER_EMAIL";
export const WEATHER_INFO_AFTER_LOGIN = "WEATHER_INFO_AFTER_LOGIN";
export const SET_WEATHER_INFO_SUCCESS = "SET_WEATHER_INFO_SUCCESS";
export const SUCCESS_DOWNLOAD = "SUCCESS_DOWNLOAD";
export const SET_DATA_TO_CHARTS = "SET_DATA_TO_CHARTS";
export const LOAD_CITIES_FROM_DB = "LOAD_CITIES_FROM_DB";
